version: '2.20.2'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: krisnadwipayana
      MYSQL_DATABASE: krisnadwipayana
    ports:
      - "8081:8081"  # Menggunakan port 3306 untuk MySQL
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Menggunakan port 8000 untuk restapi
    depends_on:
      - mysql
    restart: on-failure
    environment:
      DBHOST: mysql
      DBPORT: 3306
      DBUSER: root
      DBPASS: 123
      DBNAME: crud_go_test